# fly.toml app configuration file generated for uto-web-booker on 2026-08-06T20:57:40+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uto-web-booker'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'
  [build.args]
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "AIzaSyAkB-0o6vqtRtY2QG-YNPMQkPhu9smcHLc"
    NEXT_PUBLIC_SUPABASE_URL = "https://tadqvfnqykmjdxzpoczp.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhZHF2Zm5xeWttamR4enBvY3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NDQyNTEsImV4cCI6MjA4ODEyMDI1MX0.0Fhl0RuTFk-qtPQ5Au7iZrk9mnE8Gieth7PWdc12rxo"
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_live_51TER5DH84iWPEJxiL69ex2yw4e4yESIU0feOh1s5sb6zIKyxQh7UmoPdQTGmoTxLzhvJflPyb5yzQIhtwnjtvM9K00BOHZemUe"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
